snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^examples:'
before:
  hooks:
  - make codegen
  - go mod tidy

builds:
  - id: a3s
    main: ./cmd/a3s
    binary: a3s
    goos:
    - linux
    goarch:
    - amd64

  - id: a3sctl
    main: ./cmd/a3sctl
    binary: a3sctl
    goos:
    - linux
    goarch:
    - amd64

  - id: a3s-fips
    main: ./cmd/a3s
    binary: a3s-fips
    goos:
    - linux
    goarch:
    - amd64
    env:
    - CGO_ENABLED=1
    - GOEXPERIMENT=boringcrypto

  - id: a3sctl-fips
    main: ./cmd/a3sctl
    binary: a3sctl-fips
    goos:
    - linux
    goarch:
    - amd64
    env:
    - CGO_ENABLED=1
    - GOEXPERIMENT=boringcrypto

archives:
  - id: a3s
    builds:
    - a3s

  - id: a3sctl
    builds:
    - a3sctl

  - id: a3s-fips
    builds:
    - a3s-fips

  - id: a3sctl-fips
    builds:
    - a3sctl-fips
